In [22]:
import numpy as np

In [23]:
values = np.array([300, 310, 320, 330])
model_1 = np.array([305, 315, 300, 325])
model_2 = np.array([295, 325, 310, 340])

# Model 1

In [24]:
absolute_errors_1 = np.abs(values - model_1)
absolute_errors_1

array([ 5,  5, 20,  5])

In [25]:
square_errors_1 = (values - model_1) ** 2
square_errors_1

array([ 25,  25, 400,  25])

In [26]:
mae_1 = np.mean(absolute_errors_1)
mae_1

np.float64(8.75)

In [27]:
rmse_1 = np.sqrt(np.mean(square_errors_1))
rmse_1

np.float64(10.897247358851684)

# Model 2

In [28]:
absolute_errors_2 = np.abs(values - model_2)
absolute_errors_2

array([ 5, 15, 10, 10])

In [29]:
square_errors_2 = (values - model_2) ** 2
square_errors_2

array([ 25, 225, 100, 100])

In [30]:
mae_2 = np.mean(absolute_errors_2)
mae_2

np.float64(10.0)

In [31]:
rmse_2 = np.sqrt(np.mean(square_errors_2))
rmse_2

np.float64(10.606601717798213)

# Performance comparison

In [35]:
print(f"Model 1: \n RMSE: {rmse_1} \n MAE: {mae_1}\n")
print(f"Model 2: \n RMSE: {rmse_2} \n MAE: {mae_2}\n")

print("Model 1 is more accurate because it has less MAE")

Model 1: 
 RMSE: 10.897247358851684 
 MAE: 8.75

Model 2: 
 RMSE: 10.606601717798213 
 MAE: 10.0

Model 1 is more accurate because it has less MAE
